### ISSUE TITLE
Inverter Log

### ISSUE THREAD

**Issue by debug7878** [syssi/esphome-pipsolar#121]
Hi can you have a look at the log file attached unable to get any readings from the inverter.

Not sure if this inverter model actually will work.

[logs_inverter_run.txt](https://github.com/syssi/esphome-pipsolar/files/15025456/logs_inverter_run.txt)

![Inverter Model](https://github.com/syssi/esphome-pipsolar/assets/62151544/d9e31c71-acdd-4b44-8b8a-af004f9c7246)

**Comment by syssi** [comment]
The log contains outgoing traffic (request) only and no responses of the inverter. Possible reasons:

1. Please double check your wiring and RS232 converter
2. Wrong baud rate
3. Wrong protocol (Modbus?)
