### ISSUE TITLE
Pipsolar inverter pv1 and pv2

### ISSUE THREAD

**Issue by Caffin01** [syssi/esphome-pipsolar#123]
my pipsolar inverter has two pv inputs. how should I insert pv2 and pv Total into yaml files to see the complete parameters? Now i see only Pv1

**Comment by syssi** [comment]
Are you aware of this freature branch? https://github.com/syssi/esphome-pipsolar/tree/pip8048

Please try one of these examples:

https://github.com/syssi/esphome-pipsolar/blob/pip8048/esp32-example.yaml
https://github.com/syssi/esphome-pipsolar/blob/pip8048/esp8266-example.yaml
