### ISSUE TITLE
 Hybrid Solar inverter 8.2kw/10.2KW

### ISSUE THREAD

**Issue by Nando1497** [syssi/esphome-pipsolar#124]
Hello,
Amazing job you did .... Is-il possible to extend your work to support for this inverter: https://www.nextpowersolar.com/48V-8-2KW-10-2KW-220V-HYBRID-SOLAR-INVERTER-DUAL-PV-and-OUTPUT-pd747238888.html 
Modul:  m5stack-atom and  RS-232 

I'm willing to offer you more than a caffee.
thanks in advance

**Comment by Nando1497** [comment]
![inverter](https://github.com/syssi/esphome-pipsolar/assets/88595006/1e52d639-0dd2-4cdf-91bc-735334bc42eb)

**Comment by syssi** [comment]
Did you try the protocol test already?

**Comment by syssi** [comment]
https://diysolarforum.com/threads/victor-max-10-2-kw-rs-232-protocol.82006/

**Comment by Nando1497** [comment]
No, forgive my ignorance.. how do I do this test?

**Comment by syssi** [comment]
Please try this one and provide the output: https://github.com/syssi/esphome-pipsolar/blob/main/tests/esp8266-test-protocols.yaml

Could you ask the seller/manufacturer about some protocol details? It looks like your inverter doesn't support the PIP protocol.

**Comment by Nando1497** [comment]
[logs_inverter_run.txt](https://github.com/syssi/esphome-pipsolar/files/15324731/logs_inverter_run.txt)

**Comment by Patogoma** [comment]
I have an Anern 10.2k inverter. Is the same model and the pip8048 version works well except the QPIGS2 command. SmartESS shows correctly PV2 information.

**Comment by syssi** [comment]
Please try this YAML as next step. It should work out of the box:

https://github.com/syssi/esphome-pipsolar/blob/pip8048/esp8266-example.yaml

**Comment by patogomaII** [comment]
![image](https://github.com/syssi/esphome-pipsolar/assets/17838519/b6ce00d8-0064-411d-8fc3-41d8ed71c6d4)
No way...

**Comment by syssi** [comment]
I don't understand your comment. What's not working as expected?

**Comment by patogomaII** [comment]
current_max_charging_current doesn't work either

**Comment by patogomaII** [comment]
PV2 is unknow. QPGIS2 returns NAK

**Comment by patogomaII** [comment]
Perhaps this inverters uses a custom protocol with length and CRCs definition like this:
2.10 QPIGS2<cr>: Device general status parameters inquiry
Computer: QPIGS 2<CRC><cr>
Device: (N1N2N3N4 N6N7N8.N10 N12N13.N15N16 N18N19N20N21N22 b24b25b26b27b28b29b30b31
N33N34N35N36 N38N39N40N41 N42N43N44N45 N47N48N49.N51 N53N54.N56N57 N58N59N60N61
N63N64N65N66N67<CRC><cr>
I extract this from https://github.com/opengd/solar-sis/files/3041962/Communication.Protocol-20150924.-.Customer.pdf
and they have a same issue.

**Comment by Nando1497** [comment]
I can't compile it gives me these errors:
![image](https://github.com/syssi/esphome-pipsolar/assets/88595006/64d9f2e7-1fe6-4074-84f0-58bf76253409)
![image](https://github.com/syssi/esphome-pipsolar/assets/88595006/8941c6b4-d60a-475d-886d-b7b29860c74c)

**Comment by Nando1497** [comment]
Hi PatogomaII, do you also have this Hybrid Solar inverter 8.2kw/10.2KW model? If so, could you kindly send me the .yaml

Thank you

**Comment by patogomaII** [comment]
I have the same inverter but with other name. The yaml thar say syssi compiles and work correctly, but fails reading pv2 data. If you have compilation problems, look at the tipe of esp, pins used or something like it.

**Comment by Nando1497** [comment]
Thanks for the advice, I managed.. However, for PV2 I don't read it either but comparing the data from the inverter it seems that it only exposes PV1 by adding both values..

**Comment by patogomaII** [comment]
I compare values with the inverters screen and only shows PV1 data.

**Comment by Nando1497** [comment]
Sorry.. I confirm it does not correspond with the "KW" value "pv1_charging_power", but the "V" pv1_input_voltage value corresponds.

**Comment by patogomaII** [comment]
In my case, all the values of PV1 correspond to same values in the inverter screen.

**Comment by Nando1497** [comment]
I found this
https://esphome.io/components/pipsolar.html#output-pipsolar-set-level-action

**Comment by patogomaII** [comment]
And what do you want to do with this?

**Comment by Nando1497** [comment]
Do you receive this log?
![Screenshot 2024-05-20 alle 17 46 51](https://github.com/syssi/esphome-pipsolar/assets/88595006/723e064a-2961-467a-a534-8fc6005a95a1)

**Comment by syssi** [comment]
This warning can be ignored!

**Comment by patogomaII** [comment]
Ok. Actually, people from the PVControl+ proyect are testing a POWMR 10.2kw inverter (like us but of other father), and they are retrieving data from PV2 using 4563 and 4564 registers of serial communication.

**Comment by patogomaII** [comment]
![IMG_20240528_140031_363](https://github.com/syssi/esphome-pipsolar/assets/17838519/69661f07-6c6f-442d-afe9-d667f41f3755)
There's the data. I can take it with mqtt.

**Comment by patogomaII** [comment]
![IMG_20240528_140031_363](https://github.com/syssi/esphome-pipsolar/assets/17838519/cdfe6d91-a714-4cb9-988a-142c76d6e724)
Here they are!!!!

**Comment by patogomaII** [comment]
Ok. I have mine running with its own dongle programmed with this:
https://github.com/odya/esphome-powmr-hybrid-inverter/tree/main
Only need to modify the lines where reads pvdata and add similar code to read pv2data with registers 4563 and 4564, and voilá.

**Comment by Nando1497** [comment]
Ciao, grazie per l'aiuto. Non riesco a trovare il parametro pvdata, sto cercando nel file inverter.yaml.. Corretto ?

**Comment by Nando1497** [comment]
Hi, thanks for the help. I can't find the "pvdata" parameter, I'm looking in the inverter.yaml file.. Correct?

**Comment by patogomaII** [comment]
Look here:
https://github.com/odya/esphome-powmr-hybrid-inverter/issues/31

**Comment by Nando1497** [comment]
OK, thanks a lot
