### ISSUE TITLE
WKS evo cirlce

### ISSUE THREAD

**Issue by lhanneus** [syssi/esphome-pipsolar#138]
Any success with the WKS evo circle ?
![circle](https://github.com/user-attachments/assets/2554b903-e604-4825-a33e-357116f0f1e9)

I tried the test-protocols.yaml without answers back...

**Comment by syssi** [comment]
Do you know this issue? Please double check your wiring.

https://github.com/syssi/esphome-pipsolar/issues/68

**Comment by lhanneus** [comment]
Thanks for your answer this gives me hope. I have already soldered 2 counterfeits max3232 chip . Now, I have a functioning max3232 , I have checked with a logic analyser. But the https://github.com/syssi/esphome-pipsolar/issues/68 seems to warn off with wiring. I will order other cables and adapters to check more.
