### ISSUE TITLE
Eps8266 board NodeMCU V3 can working?

### ISSUE THREAD

**Issue by tieptute2k** [syssi/esphome-pipsolar#142]
Your application can working with Eps8266 board NodeMCU V3 ?

**Comment by syssi** [comment]
Yes.

**Comment by tieptute2k** [comment]
How should I configure .yaml? Thank you

**Comment by syssi** [comment]
Just take this one: https://github.com/syssi/esphome-pipsolar/blob/main/esp8266-example.yaml

**Comment by tieptute2k** [comment]
esp8266:
  board: d1_mini

How should I configure for NodeMCU V3?

**Comment by syssi** [comment]
`nodemcuv2` is probably a good choice but it's not very important. See https://esphome.io/components/esp8266.html#configuration-variables

> The PlatformIO board ID that should be used. Choose the appropriate board from [this list](https://registry.platformio.org/platforms/platformio/espressif8266/boards) (the icon next to the name can be used to copy the board ID). This only affects pin aliases, flash size and some internal settings, if unsure choose a generic board from Espressif such as esp01_1m.

**Comment by tieptute2k** [comment]
Great! Thank you very much.....
