### ISSUE TITLE
PV Monitoring

### ISSUE THREAD

**Issue by vpritulin** [syssi/esphome-pipsolar#158]
Hi, I have daxtromn with 2 PV. I tried to use this configuration https://github.com/syssi/esphome-pipsolar/blob/pip8048/esp32-example.yaml but I get an error. Pipsolar does not have information from PV2. I tried to find the address for PV2, but without success

![image](https://github.com/user-attachments/assets/5b52f2af-c96a-4f85-a842-8a22ebc2c133)

**Comment by syssi** [comment]
Did you try the `pip8048` branch? It supports two strings.

**Comment by vpritulin** [comment]
@syssi yes, but it didn't help 
my yaml file [yaml.txt](https://github.com/user-attachments/files/17616158/yaml.txt)
 
![image](https://github.com/user-attachments/assets/f0dec66f-8bc0-430e-b50a-d47c17db1b23)

**Comment by syssi** [comment]
The mentioned `select` section is missing. You have to add a single `select` entity at least:

```
select:
  - platform: pipsolar
    pipsolar_id: inverter0
    output_source_priority:
      id: inverter0_output_source_priority_select
      name: inverter0_output_source_priority_select
      optionsmap:
        "Utility first": "POP00"
        "Solar only": "POP01"
        "Solar Battery Utility": "POP02"
      statusmap:
        "0": "Utility first"
        "1": "Solar only"
        "2": "Solar Battery Utility"
```

See https://github.com/syssi/esphome-pipsolar/blob/pip8048/esp32-example.yaml

**Comment by vpritulin** [comment]
I don't get data from pv2 it's displayed as unknown

<<< "(222.5 50.0 230.1 49.9 0437 0386 004 448 56.50 000 097 0049 01.4 348.9 00.00 00000 00010110 00 00 00509 110\x9FH\r"

**Comment by syssi** [comment]
Could you provide some more lines of the log? The single line without context doesn't help. Does your inverter respond to the `QPIGS2` request?

**Comment by vpritulin** [comment]
I have attached the full log.
[logs_ibconnect_logs.txt](https://github.com/user-attachments/files/17617656/logs_ibconnect_logs.txt)

**Comment by syssi** [comment]
Your inverter rejects the `QPIGS2` request:

```
[13:46:31][D][uart_debug:158]: >>> "QPIGS2h-\r"
[13:46:31][D][uart_debug:158]: <<< "(NAKss\r"
```

`QPIGS2` is the command to retrieve the measurements of the second PV string. Did you check the other issues of this github project? There are more people with the same problem.

**Comment by vpritulin** [comment]
yes, I checked this issue https://github.com/syssi/esphome-pipsolar/issues/149. But as I understood, the person connected the module to the ESP and receives data from it

**Comment by syssi** [comment]
At the end the inverter was interfaced using Modbus:

https://github.com/syssi/esphome-pipsolar/issues/149#issuecomment-2359224216
https://github.com/odya/esphome-powmr-hybrid-inverter/issues/31

**Comment by vpritulin** [comment]
@syssi Thanks for your help. Another repository helped me. Closing this issue

**Comment by syssi** [comment]
Could you provide the solution here / point to the repo?
