### ISSUE TITLE
PIP8048 Faults Present

### ISSUE THREAD

**Issue by bHOLDher** [syssi/esphome-pipsolar#162]
Hi,

Please, when you get a moment, on the PIP8048 branch, and one or two other branches, in components/pipsolar/pipsolar.cpp line 594 sets 
`this->value_faults_present_ = true;` 
then following this line if faults are detected, the value is set to true again. Therefore the faults_present state is always true. 

Please change the default to false on line 594.

Thanks

**Comment by SeByDocKy** [comment]
Done ...
