### ISSUE TITLE
Easun 8kw pv input no data.

### ISSUE THREAD

**Issue by idanny50** [syssi/esphome-pipsolar#30]

**Comment by idanny50** [comment]
my inverter has 2 PV inputs.

**Comment by idanny50** [comment]
I added more detailed log! 
[logs_easun_logs (1).txt](https://github.com/syssi/esphome-pipsolar/files/9671926/logs_easun_logs.1.txt)

**Comment by syssi** [comment]
The first log was better because the debug mode of the `uart` component was enabled. The second log doesn't contain `uart_debug` log lines.

**Comment by idanny50** [comment]
another log!
[Uploading logs_easun_logs 2.txt…]()

**Comment by syssi** [comment]
The last upload is broken. Could you give it another try?

**Comment by syssi** [comment]
This branch supports two PV strings:

```
external_components:
  - source: github://syssi/esphome-pipsolar@pip8048
    refresh: 0s
``` 

https://github.com/syssi/esphome-pipsolar/blob/pip8048/esp8266-example.yaml

**Comment by idanny50** [comment]
All seems ok now! I have strings now! Thank you for your support!
