### ISSUE TITLE
Connections for Voltronic MK IV

### ISSUE THREAD

**Issue by nuvolare12** [syssi/esphome-pipsolar#40]
Hello Sissi, i wish to connect my Axpert MK IV with Home Assistant, i have a different connector, can you help me step by step to connect it? I attaced the my connection, i don't have the step down for the moment  thank you
![IMG_20221123_201900_943](https://user-images.githubusercontent.com/116510362/203869640-99d924b9-6b8b-4ed8-a59b-42dbd94655dd.jpg)
![IMG_20221123_203134_006](https://user-images.githubusercontent.com/116510362/203869645-eef9264e-815e-4ead-8c17-6a9cf4da5297.jpg)
![IMG_20221123_203210_339](https://user-images.githubusercontent.com/116510362/203869646-65ea31f5-f255-4756-8afd-fd69cf241717.jpg)
![IMG_20221124_103503_145](https://user-images.githubusercontent.com/116510362/203869651-aa26438a-0ae8-4864-972e-bf98d14ddb08.jpg)

**Comment by nuvolare12** [comment]
I'm so getting timout 
![esp](https://user-images.githubusercontent.com/116510362/205876528-8dfd68d9-0be6-47b7-9fa5-33ec59aa7b93.png)

**Comment by nuvolare12** [comment]
![IMG_20221206_104819](https://user-images.githubusercontent.com/116510362/205877649-8ab1ce59-a646-4a13-b33c-79b558bf749f.jpg)
And this are the connection

**Comment by VirtualFab** [comment]
Ok, my fault, I didn't recognized in my logs that for example
[09:57:35][D][uart_debug:158]: >>> "QPIGS\xB7\xA9\r"
[09:57:35][D][pipsolar:838]: Sending polling command : QPIGS with length 5
[09:57:35][D][uart_debug:158]: <<< "QPIGS\xB7\xA9\r"
I was receiving the same exact data I was sending, so it was clear Tx and Rx were somehow in a loop connection.
I simply reswapped Rx and Tx (that I swapped on the ESP32 side) and then swapped them on the MAX3232 pins on the RS-232 side-
This led to the correct connection:

> [11:11:39][D][uart_debug:158]: >>> "QPIGS\xB7\xA9\r"
> [11:11:39][D][pipsolar:838]: Sending polling command : QPIGS with length 5
> [11:11:40][D][uart_debug:158]: **<<< "(233.7 49.9 233.7 49.9 0771 0750 013 376 50.20 011 026 0027 01.9 334.0 00.00 00000 00010111 00 00 00663 010\xD3}\r**"
> [11:11:40][D][pipsolar:772]: checking crc on incoming message
> [11:11:40][D][pipsolar:775]: CRC OK

So now the whole thing is working, thank you!

**Comment by nuvolare12** [comment]
Hello VirtualFab, i tried to invert RX with TX, and now it's working. For the Power supply i use the usb connector for the mobile phone, but i want to use a Step-down

**Comment by syssi** [comment]
Summary: The Axpert MK IV / Voltronic MK IV is compatible with the `pipsolar` component.
