### ISSUE TITLE
esp01 supported?

### ISSUE THREAD

**Issue by shamirahim111** [syssi/esphome-pipsolar#92]
Hi.

can we use an ESP01 because its a bit cheaper?

**Comment by shamirahim111** [comment]
https://robu.in/product/esp-01-esp8266-serial-wifi-wireless-transceiver-module/

like this?

**Comment by syssi** [comment]
It's cheaper but you have to care about a stable power supply and it's more complicated to flash the ESP + apply a proper boot configuration. The ESP is compatible in general.

**Comment by shamirahim111** [comment]
@syssi okay cool. i will try to purchase both and see if https://robu.in/product/d1-mini-v2-nodemcu-4m-bytes-lua-wifi-internet-of-things-development-board-based-esp8266/ works any better. it also has in built power so yeah.

one question i have.  
this is the configuration that seems to be working for me. 
https://solaranzeige.de/phpBB3/download/Phocos%20Any-Grid.json

![Screenshot 2023-11-09 at 17-29-50 Category Equipment_Dashboards_Connection type_Note - Solar display _ PV Monitor](https://github.com/syssi/esphome-pipsolar/assets/149858437/351c8f5e-4428-4443-a85b-bd3c55438f94)

you think this would work?

**Comment by syssi** [comment]
I don't know. I cannot find any details about the used protocol in the `Phocos Any-Grid.json`. Do I miss something?

**Comment by shamirahim111** [comment]
@syssi  hey. what about config from this repo? https://github.com/wolffshots/phocus

**Comment by shamirahim111** [comment]
@syssi i have bought one esp8266 nodemcu v3, will test it out

**Comment by shamirahim111** [comment]
@syssi what about this specific line 
https://github.com/DeBaschdi/solar_config/blob/f329f2a034c52264c6883e0be857b70dde9807a5/www/html/multi_usb_init.php#L345

**Comment by shamirahim111** [comment]
thanks.  i think i am able to connect via esp8266. only thing missing is to figure out protocol. thanks
